/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AddItemBlockRuleInput = {
  ruleType: string;
  value: string;
  domain?: string;
};

export type AddItemBlockRulesRequest = {
  rules: AddItemBlockRuleInput[];
};

export type AddURLParsingRuleRequest = {
  domain: string;
  ruleType: string;
  pattern: string;
};

export type URLParsingRule = {
  id: string;
  domain: string;
  ruleType: string;
  pattern: string;
};

export type AddURLParsingRuleResponse = {
  rule: URLParsingRule;
};

export type ApiError = {
  code: string;
  message: string;
};

export type CreateFeedRequest = {
  url: string;
  tagIds: string[];
};

export type Tag = {
  id: string;
  name: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
  unreadCount: string;
  feedCount: string;
};

export type Feed = {
  id: string;
  url: string;
  link?: string;
  title: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  lastFetchedAt?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  nextFetchAt?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
  tags: Tag[];
  unreadCount: string;
};

export type CreateFeedResponse = {
  feed: Feed;
};

export type CreateIgnoreWindowRequest = {
  name: string;
  startTime: string;
  endTime: string;
  daysOfWeek: number[];
  timezone: string;
};

export type IgnoreWindow = {
  id: string;
  name: string;
  startTime: string;
  endTime: string;
  daysOfWeek: number[];
  timezone: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
};

export type CreateIgnoreWindowResponse = {
  ignoreWindow: IgnoreWindow;
};

export type CreateTagRequest = {
  name: string;
};

export type CreateTagResponse = {
  tag: Tag;
};

export type ExportOpmlRequest = {
  ids: string[];
};

export type ExportOpmlResponse = {
  opmlContent: string;
};

export type FeedFetchStatus = {
  feedId: string;
  success: boolean;
  /**
   * @description
   * Format: `int32`
   * @type integer
   */
  newItemsCount: number;
  errorMessage?: string;
};

export type FeedIgnoreWindow = {
  feedId: string;
  ignoreWindowId: string;
};

export type FeedTag = {
  feedId: string;
  tagId: string;
};

export type ItemFeed = {
  id: string;
  title: string;
};

export type Item = {
  id: string;
  url: string;
  title: string;
  description: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  publishedAt?: string;
  feedId: string;
  isRead: boolean;
  author: string;
  content: string;
  imageUrl: string;
  categories: string;
  feeds?: ItemFeed[];
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
};

export type GetItemResponse = {
  item?: Item;
};

export type ImportFailedFeed = {
  url: string;
  errorMessage: string;
};

export type ImportOpmlRequest = {
  opmlContent: string;
};

export type ImportOpmlResponse = {
  /**
   * @description
   * Format: `int32`
   * @type integer
   */
  total: number;
  /**
   * @description
   * Format: `int32`
   * @type integer
   */
  success: number;
  /**
   * @description
   * Format: `int32`
   * @type integer
   */
  skipped: number;
  failedFeeds: ImportFailedFeed[];
};

export type ItemBlockRule = {
  id: string;
  ruleType: string;
  value: string;
  domain?: string;
};

export type ItemRead = {
  itemId: string;
  isRead: boolean;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
};

export type ListFeedIgnoreWindowsResponse = {
  feedIgnoreWindows: FeedIgnoreWindow[];
};

export type ListFeedTagsResponse = {
  feedTags: FeedTag[];
};

export type ListFeedsResponse = {
  feeds: Feed[];
};

export type ListIgnoreWindowsResponse = {
  ignoreWindows: IgnoreWindow[];
};

export type ListItemBlockRulesResponse = {
  rules: ItemBlockRule[];
};

export type ListItemReadResponse = {
  itemReads: ItemRead[];
  nextPageToken: string;
};

export type ListItemsResponse = {
  items: Item[];
  nextPageToken: string;
};

export type TagIgnoreWindow = {
  tagId: string;
  ignoreWindowId: string;
};

export type ListTagIgnoreWindowsResponse = {
  tagIgnoreWindows: TagIgnoreWindow[];
};

export type ListTagsResponse = {
  tags: Tag[];
  totalUnreadCount: string;
};

export type ListURLParsingRulesResponse = {
  rules: URLParsingRule[];
};

export type ManageFeedIgnoreWindowsRequest = {
  feedIds: string[];
  addIgnoreWindowIds: string[];
  removeIgnoreWindowIds: string[];
};

export type ManageFeedTagsRequest = {
  feedIds: string[];
  addTagIds: string[];
  removeTagIds: string[];
};

export type ManageTagIgnoreWindowsRequest = {
  tagIds: string[];
  addIgnoreWindowIds: string[];
  removeIgnoreWindowIds: string[];
};

export type RefreshFeedsRequest = {
  ids: string[];
};

export type RefreshFeedsResponse = {
  results: FeedFetchStatus[];
};

export type SuspendFeedsRequest = {
  ids: string[];
  suspendSeconds: string;
};

export type UpdateIgnoreWindowRequest = {
  name?: string;
  startTime?: string;
  endTime?: string;
  daysOfWeek?: number[];
  timezone?: string;
};

export type UpdateIgnoreWindowResponse = {
  ignoreWindow: IgnoreWindow;
};

export type UpdateItemStatusRequest = {
  ids: string[];
  isRead?: boolean;
};

export type BlockRulesListStatus200 = ListItemBlockRulesResponse;

export type BlockRulesListStatus500 = ApiError;

export type BlockRulesListOptions = {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
};

export type BlockRulesListResponses = {
  "200": BlockRulesListStatus200;
  "500": BlockRulesListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type BlockRulesListResponse =
  | BlockRulesListStatus200
  | BlockRulesListStatus500;

export type BlockRulesAddStatus200 = unknown;

export type BlockRulesAddStatus500 = ApiError;

export type BlockRulesAddBody = AddItemBlockRulesRequest;

export type BlockRulesAddOptions = {
  body: BlockRulesAddBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type BlockRulesAddResponses = {
  "200": BlockRulesAddStatus200;
  "500": BlockRulesAddStatus500;
};

/**
 * @description Union of all possible responses
 */
export type BlockRulesAddResponse =
  | BlockRulesAddStatus200
  | BlockRulesAddStatus500;

export type BlockRulesDeletePath = {
  id: string;
};

export type BlockRulesDeleteStatus200 = unknown;

export type BlockRulesDeleteStatus500 = ApiError;

export type BlockRulesDeleteOptions = {
  body?: never;
  path: BlockRulesDeletePath;
  query?: never;
  headers?: never;
};

export type BlockRulesDeleteResponses = {
  "200": BlockRulesDeleteStatus200;
  "500": BlockRulesDeleteStatus500;
};

/**
 * @description Union of all possible responses
 */
export type BlockRulesDeleteResponse =
  | BlockRulesDeleteStatus200
  | BlockRulesDeleteStatus500;

export type FeedIgnoreWindowsListQuery = {
  feedId?: string;
  ignoreWindowId?: string;
};

export type FeedIgnoreWindowsListStatus200 = ListFeedIgnoreWindowsResponse;

export type FeedIgnoreWindowsListStatus500 = ApiError;

export type FeedIgnoreWindowsListOptions = {
  body?: never;
  path?: never;
  query?: FeedIgnoreWindowsListQuery;
  headers?: never;
};

export type FeedIgnoreWindowsListResponses = {
  "200": FeedIgnoreWindowsListStatus200;
  "500": FeedIgnoreWindowsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedIgnoreWindowsListResponse =
  | FeedIgnoreWindowsListStatus200
  | FeedIgnoreWindowsListStatus500;

export type FeedIgnoreWindowsManageStatus200 = unknown;

export type FeedIgnoreWindowsManageStatus500 = ApiError;

export type FeedIgnoreWindowsManageBody = ManageFeedIgnoreWindowsRequest;

export type FeedIgnoreWindowsManageOptions = {
  body: FeedIgnoreWindowsManageBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedIgnoreWindowsManageResponses = {
  "200": FeedIgnoreWindowsManageStatus200;
  "500": FeedIgnoreWindowsManageStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedIgnoreWindowsManageResponse =
  | FeedIgnoreWindowsManageStatus200
  | FeedIgnoreWindowsManageStatus500;

export type FeedTagsListQuery = {
  feedId?: string;
  tagId?: string;
};

export type FeedTagsListStatus200 = ListFeedTagsResponse;

export type FeedTagsListStatus500 = ApiError;

export type FeedTagsListOptions = {
  body?: never;
  path?: never;
  query?: FeedTagsListQuery;
  headers?: never;
};

export type FeedTagsListResponses = {
  "200": FeedTagsListStatus200;
  "500": FeedTagsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedTagsListResponse =
  | FeedTagsListStatus200
  | FeedTagsListStatus500;

export type FeedTagsManageStatus200 = unknown;

export type FeedTagsManageStatus500 = ApiError;

export type FeedTagsManageBody = ManageFeedTagsRequest;

export type FeedTagsManageOptions = {
  body: FeedTagsManageBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedTagsManageResponses = {
  "200": FeedTagsManageStatus200;
  "500": FeedTagsManageStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedTagsManageResponse =
  | FeedTagsManageStatus200
  | FeedTagsManageStatus500;

export type FeedsListQuery = {
  tagId?: string;
};

export type FeedsListStatus200 = ListFeedsResponse;

export type FeedsListStatus500 = ApiError;

export type FeedsListOptions = {
  body?: never;
  path?: never;
  query?: FeedsListQuery;
  headers?: never;
};

export type FeedsListResponses = {
  "200": FeedsListStatus200;
  "500": FeedsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsListResponse = FeedsListStatus200 | FeedsListStatus500;

export type FeedsCreateStatus200 = CreateFeedResponse;

export type FeedsCreateStatus500 = ApiError;

export type FeedsCreateBody = CreateFeedRequest;

export type FeedsCreateOptions = {
  body: FeedsCreateBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedsCreateResponses = {
  "200": FeedsCreateStatus200;
  "500": FeedsCreateStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsCreateResponse = FeedsCreateStatus200 | FeedsCreateStatus500;

export type FeedsExportOpmlStatus200 = ExportOpmlResponse;

export type FeedsExportOpmlStatus500 = ApiError;

export type FeedsExportOpmlBody = ExportOpmlRequest;

export type FeedsExportOpmlOptions = {
  body: FeedsExportOpmlBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedsExportOpmlResponses = {
  "200": FeedsExportOpmlStatus200;
  "500": FeedsExportOpmlStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsExportOpmlResponse =
  | FeedsExportOpmlStatus200
  | FeedsExportOpmlStatus500;

export type FeedsImportOpmlStatus200 = ImportOpmlResponse;

export type FeedsImportOpmlStatus500 = ApiError;

export type FeedsImportOpmlBody = ImportOpmlRequest;

export type FeedsImportOpmlOptions = {
  body: FeedsImportOpmlBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedsImportOpmlResponses = {
  "200": FeedsImportOpmlStatus200;
  "500": FeedsImportOpmlStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsImportOpmlResponse =
  | FeedsImportOpmlStatus200
  | FeedsImportOpmlStatus500;

export type FeedsRefreshStatus200 = RefreshFeedsResponse;

export type FeedsRefreshStatus500 = ApiError;

export type FeedsRefreshBody = RefreshFeedsRequest;

export type FeedsRefreshOptions = {
  body: FeedsRefreshBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedsRefreshResponses = {
  "200": FeedsRefreshStatus200;
  "500": FeedsRefreshStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsRefreshResponse =
  | FeedsRefreshStatus200
  | FeedsRefreshStatus500;

export type FeedsSuspendStatus200 = unknown;

export type FeedsSuspendStatus500 = ApiError;

export type FeedsSuspendBody = SuspendFeedsRequest;

export type FeedsSuspendOptions = {
  body: FeedsSuspendBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type FeedsSuspendResponses = {
  "200": FeedsSuspendStatus200;
  "500": FeedsSuspendStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsSuspendResponse =
  | FeedsSuspendStatus200
  | FeedsSuspendStatus500;

export type FeedsDeletePath = {
  id: string;
};

export type FeedsDeleteStatus200 = unknown;

export type FeedsDeleteStatus500 = ApiError;

export type FeedsDeleteOptions = {
  body?: never;
  path: FeedsDeletePath;
  query?: never;
  headers?: never;
};

export type FeedsDeleteResponses = {
  "200": FeedsDeleteStatus200;
  "500": FeedsDeleteStatus500;
};

/**
 * @description Union of all possible responses
 */
export type FeedsDeleteResponse = FeedsDeleteStatus200 | FeedsDeleteStatus500;

export type IgnoreWindowsListStatus200 = ListIgnoreWindowsResponse;

export type IgnoreWindowsListStatus500 = ApiError;

export type IgnoreWindowsListOptions = {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
};

export type IgnoreWindowsListResponses = {
  "200": IgnoreWindowsListStatus200;
  "500": IgnoreWindowsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type IgnoreWindowsListResponse =
  | IgnoreWindowsListStatus200
  | IgnoreWindowsListStatus500;

export type IgnoreWindowsCreateStatus200 = CreateIgnoreWindowResponse;

export type IgnoreWindowsCreateStatus500 = ApiError;

export type IgnoreWindowsCreateBody = CreateIgnoreWindowRequest;

export type IgnoreWindowsCreateOptions = {
  body: IgnoreWindowsCreateBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type IgnoreWindowsCreateResponses = {
  "200": IgnoreWindowsCreateStatus200;
  "500": IgnoreWindowsCreateStatus500;
};

/**
 * @description Union of all possible responses
 */
export type IgnoreWindowsCreateResponse =
  | IgnoreWindowsCreateStatus200
  | IgnoreWindowsCreateStatus500;

export type IgnoreWindowsUpdatePath = {
  id: string;
};

export type IgnoreWindowsUpdateStatus200 = UpdateIgnoreWindowResponse;

export type IgnoreWindowsUpdateStatus500 = ApiError;

export type IgnoreWindowsUpdateBody = UpdateIgnoreWindowRequest;

export type IgnoreWindowsUpdateOptions = {
  body: IgnoreWindowsUpdateBody;
  path: IgnoreWindowsUpdatePath;
  query?: never;
  headers?: never;
};

export type IgnoreWindowsUpdateResponses = {
  "200": IgnoreWindowsUpdateStatus200;
  "500": IgnoreWindowsUpdateStatus500;
};

/**
 * @description Union of all possible responses
 */
export type IgnoreWindowsUpdateResponse =
  | IgnoreWindowsUpdateStatus200
  | IgnoreWindowsUpdateStatus500;

export type IgnoreWindowsDeletePath = {
  id: string;
};

export type IgnoreWindowsDeleteStatus200 = unknown;

export type IgnoreWindowsDeleteStatus500 = ApiError;

export type IgnoreWindowsDeleteOptions = {
  body?: never;
  path: IgnoreWindowsDeletePath;
  query?: never;
  headers?: never;
};

export type IgnoreWindowsDeleteResponses = {
  "200": IgnoreWindowsDeleteStatus200;
  "500": IgnoreWindowsDeleteStatus500;
};

/**
 * @description Union of all possible responses
 */
export type IgnoreWindowsDeleteResponse =
  | IgnoreWindowsDeleteStatus200
  | IgnoreWindowsDeleteStatus500;

export type ItemReadsListQuery = {
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  since?: string;
  /**
   * @description
   * Format: `int32`
   * @type integer | undefined
   */
  pageSize?: number;
  pageToken?: string;
};

export type ItemReadsListStatus200 = ListItemReadResponse;

export type ItemReadsListStatus500 = ApiError;

export type ItemReadsListOptions = {
  body?: never;
  path?: never;
  query?: ItemReadsListQuery;
  headers?: never;
};

export type ItemReadsListResponses = {
  "200": ItemReadsListStatus200;
  "500": ItemReadsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type ItemReadsListResponse =
  | ItemReadsListStatus200
  | ItemReadsListStatus500;

export type ItemsListQuery = {
  feedId?: string;
  isRead?: boolean;
  tagId?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  since?: string;
  /**
   * @description
   * Format: `int32`
   * @type integer | undefined
   */
  pageSize?: number;
  pageToken?: string;
};

export type ItemsListStatus200 = ListItemsResponse;

export type ItemsListStatus500 = ApiError;

export type ItemsListOptions = {
  body?: never;
  path?: never;
  query?: ItemsListQuery;
  headers?: never;
};

export type ItemsListResponses = {
  "200": ItemsListStatus200;
  "500": ItemsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type ItemsListResponse = ItemsListStatus200 | ItemsListStatus500;

export type ItemsUpdateStatusStatus200 = unknown;

export type ItemsUpdateStatusStatus500 = ApiError;

export type ItemsUpdateStatusBody = UpdateItemStatusRequest;

export type ItemsUpdateStatusOptions = {
  body: ItemsUpdateStatusBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type ItemsUpdateStatusResponses = {
  "200": ItemsUpdateStatusStatus200;
  "500": ItemsUpdateStatusStatus500;
};

/**
 * @description Union of all possible responses
 */
export type ItemsUpdateStatusResponse =
  | ItemsUpdateStatusStatus200
  | ItemsUpdateStatusStatus500;

export type ItemsGetPath = {
  id: string;
};

export type ItemsGetStatus200 = GetItemResponse;

export type ItemsGetStatus500 = ApiError;

export type ItemsGetOptions = {
  body?: never;
  path: ItemsGetPath;
  query?: never;
  headers?: never;
};

export type ItemsGetResponses = {
  "200": ItemsGetStatus200;
  "500": ItemsGetStatus500;
};

/**
 * @description Union of all possible responses
 */
export type ItemsGetResponse = ItemsGetStatus200 | ItemsGetStatus500;

export type TagIgnoreWindowsListQuery = {
  tagId?: string;
  ignoreWindowId?: string;
};

export type TagIgnoreWindowsListStatus200 = ListTagIgnoreWindowsResponse;

export type TagIgnoreWindowsListStatus500 = ApiError;

export type TagIgnoreWindowsListOptions = {
  body?: never;
  path?: never;
  query?: TagIgnoreWindowsListQuery;
  headers?: never;
};

export type TagIgnoreWindowsListResponses = {
  "200": TagIgnoreWindowsListStatus200;
  "500": TagIgnoreWindowsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type TagIgnoreWindowsListResponse =
  | TagIgnoreWindowsListStatus200
  | TagIgnoreWindowsListStatus500;

export type TagIgnoreWindowsManageStatus200 = unknown;

export type TagIgnoreWindowsManageStatus500 = ApiError;

export type TagIgnoreWindowsManageBody = ManageTagIgnoreWindowsRequest;

export type TagIgnoreWindowsManageOptions = {
  body: TagIgnoreWindowsManageBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type TagIgnoreWindowsManageResponses = {
  "200": TagIgnoreWindowsManageStatus200;
  "500": TagIgnoreWindowsManageStatus500;
};

/**
 * @description Union of all possible responses
 */
export type TagIgnoreWindowsManageResponse =
  | TagIgnoreWindowsManageStatus200
  | TagIgnoreWindowsManageStatus500;

export type TagsListStatus200 = ListTagsResponse;

export type TagsListStatus500 = ApiError;

export type TagsListOptions = {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
};

export type TagsListResponses = {
  "200": TagsListStatus200;
  "500": TagsListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type TagsListResponse = TagsListStatus200 | TagsListStatus500;

export type TagsCreateStatus200 = CreateTagResponse;

export type TagsCreateStatus500 = ApiError;

export type TagsCreateBody = CreateTagRequest;

export type TagsCreateOptions = {
  body: TagsCreateBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type TagsCreateResponses = {
  "200": TagsCreateStatus200;
  "500": TagsCreateStatus500;
};

/**
 * @description Union of all possible responses
 */
export type TagsCreateResponse = TagsCreateStatus200 | TagsCreateStatus500;

export type TagsDeletePath = {
  id: string;
};

export type TagsDeleteStatus200 = unknown;

export type TagsDeleteStatus500 = ApiError;

export type TagsDeleteOptions = {
  body?: never;
  path: TagsDeletePath;
  query?: never;
  headers?: never;
};

export type TagsDeleteResponses = {
  "200": TagsDeleteStatus200;
  "500": TagsDeleteStatus500;
};

/**
 * @description Union of all possible responses
 */
export type TagsDeleteResponse = TagsDeleteStatus200 | TagsDeleteStatus500;

export type URLRulesListStatus200 = ListURLParsingRulesResponse;

export type URLRulesListStatus500 = ApiError;

export type URLRulesListOptions = {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
};

export type URLRulesListResponses = {
  "200": URLRulesListStatus200;
  "500": URLRulesListStatus500;
};

/**
 * @description Union of all possible responses
 */
export type URLRulesListResponse =
  | URLRulesListStatus200
  | URLRulesListStatus500;

export type URLRulesAddStatus200 = AddURLParsingRuleResponse;

export type URLRulesAddStatus500 = ApiError;

export type URLRulesAddBody = AddURLParsingRuleRequest;

export type URLRulesAddOptions = {
  body: URLRulesAddBody;
  path?: never;
  query?: never;
  headers?: never;
};

export type URLRulesAddResponses = {
  "200": URLRulesAddStatus200;
  "500": URLRulesAddStatus500;
};

/**
 * @description Union of all possible responses
 */
export type URLRulesAddResponse = URLRulesAddStatus200 | URLRulesAddStatus500;

export type URLRulesDeletePath = {
  id: string;
};

export type URLRulesDeleteStatus200 = unknown;

export type URLRulesDeleteStatus500 = ApiError;

export type URLRulesDeleteOptions = {
  body?: never;
  path: URLRulesDeletePath;
  query?: never;
  headers?: never;
};

export type URLRulesDeleteResponses = {
  "200": URLRulesDeleteStatus200;
  "500": URLRulesDeleteStatus500;
};

/**
 * @description Union of all possible responses
 */
export type URLRulesDeleteResponse =
  | URLRulesDeleteStatus200
  | URLRulesDeleteStatus500;
