/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AddItemBlockRuleInput = {
  /**
   * @type string
   */
  ruleType: string;
  /**
   * @type string
   */
  value: string;
  /**
   * @type string | undefined
   */
  domain?: string;
};

export type AddItemBlockRulesRequest = {
  /**
   * @type array
   */
  rules: AddItemBlockRuleInput[];
};

export type AddURLParsingRuleRequest = {
  /**
   * @type string
   */
  domain: string;
  /**
   * @type string
   */
  ruleType: string;
  /**
   * @type string
   */
  pattern: string;
};

export type URLParsingRule = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  domain: string;
  /**
   * @type string
   */
  ruleType: string;
  /**
   * @type string
   */
  pattern: string;
};

export type AddURLParsingRuleResponse = {
  /**
   * @type object
   */
  rule: URLParsingRule;
};

export type ApiError = {
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  message: string;
};

export type CreateFeedRequest = {
  /**
   * @type string
   */
  url: string;
  /**
   * @type array
   */
  tagIds: string[];
};

export type Tag = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
  /**
   * @type string
   */
  unreadCount: string;
  /**
   * @type string
   */
  feedCount: string;
};

export type Feed = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  url: string;
  /**
   * @type string | undefined
   */
  link?: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string | undefined, date-time
   */
  lastFetchedAt?: string;
  /**
   * @type string | undefined, date-time
   */
  nextFetchAt?: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
  /**
   * @type array
   */
  tags: Tag[];
  /**
   * @type string
   */
  unreadCount: string;
};

export type CreateFeedResponse = {
  /**
   * @type object
   */
  feed: Feed;
};

export type CreateTagRequest = {
  /**
   * @type string
   */
  name: string;
};

export type CreateTagResponse = {
  /**
   * @type object
   */
  tag: Tag;
};

export type ExportOpmlRequest = {
  /**
   * @type array
   */
  ids: string[];
};

export type ExportOpmlResponse = {
  /**
   * @type string, byte
   */
  opmlContent: string;
};

export type FeedFetchStatus = {
  /**
   * @type string
   */
  feedId: string;
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type integer, int32
   */
  newItemsCount: number;
  /**
   * @type string | undefined
   */
  errorMessage?: string;
};

export type FeedTag = {
  /**
   * @type string
   */
  feedId: string;
  /**
   * @type string
   */
  tagId: string;
};

export type ItemFeed = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  title: string;
};

export type Item = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  url: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type string | undefined, date-time
   */
  publishedAt?: string;
  /**
   * @type string
   */
  feedId: string;
  /**
   * @type boolean
   */
  isRead: boolean;
  /**
   * @type string
   */
  author: string;
  /**
   * @type string
   */
  content: string;
  /**
   * @type string
   */
  imageUrl: string;
  /**
   * @type string
   */
  categories: string;
  /**
   * @type array | undefined
   */
  feeds?: ItemFeed[];
  /**
   * @type string, date-time
   */
  createdAt: string;
};

export type GetItemResponse = {
  /**
   * @type object | undefined
   */
  item?: Item;
};

export type ImportFailedFeed = {
  /**
   * @type string
   */
  url: string;
  /**
   * @type string
   */
  errorMessage: string;
};

export type ImportOpmlRequest = {
  /**
   * @type string, byte
   */
  opmlContent: string;
};

export type ImportOpmlResponse = {
  /**
   * @type integer, int32
   */
  total: number;
  /**
   * @type integer, int32
   */
  success: number;
  /**
   * @type integer, int32
   */
  skipped: number;
  /**
   * @type array
   */
  failedFeeds: ImportFailedFeed[];
};

export type ItemBlockRule = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  ruleType: string;
  /**
   * @type string
   */
  value: string;
  /**
   * @type string | undefined
   */
  domain?: string;
};

export type ItemRead = {
  /**
   * @type string
   */
  itemId: string;
  /**
   * @type boolean
   */
  isRead: boolean;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};

export type ListFeedTagsResponse = {
  /**
   * @type array
   */
  feedTags: FeedTag[];
};

export type ListFeedsResponse = {
  /**
   * @type array
   */
  feeds: Feed[];
};

export type ListItemBlockRulesResponse = {
  /**
   * @type array
   */
  rules: ItemBlockRule[];
};

export type ListItemReadResponse = {
  /**
   * @type array
   */
  itemReads: ItemRead[];
  /**
   * @type string
   */
  nextPageToken: string;
};

export type ListItemsResponse = {
  /**
   * @type array
   */
  items: Item[];
  /**
   * @type string
   */
  nextPageToken: string;
};

export type ListTagsResponse = {
  /**
   * @type array
   */
  tags: Tag[];
  /**
   * @type string
   */
  totalUnreadCount: string;
};

export type ListURLParsingRulesResponse = {
  /**
   * @type array
   */
  rules: URLParsingRule[];
};

export type ManageFeedTagsRequest = {
  /**
   * @type array
   */
  feedIds: string[];
  /**
   * @type array
   */
  addTagIds: string[];
  /**
   * @type array
   */
  removeTagIds: string[];
};

export type RefreshFeedsRequest = {
  /**
   * @type array
   */
  ids: string[];
};

export type RefreshFeedsResponse = {
  /**
   * @type array
   */
  results: FeedFetchStatus[];
};

export type SuspendFeedsRequest = {
  /**
   * @type array
   */
  ids: string[];
  /**
   * @type string
   */
  suspendSeconds: string;
};

export type UpdateItemStatusRequest = {
  /**
   * @type array
   */
  ids: string[];
  /**
   * @type boolean | undefined
   */
  isRead?: boolean;
};

/**
 * @description The request has succeeded.
 */
export type BlockRulesList200 = ListItemBlockRulesResponse;

/**
 * @description Server error
 */
export type BlockRulesList500 = ApiError;

export type BlockRulesListQueryResponse = BlockRulesList200;

export type BlockRulesListQuery = {
  Response: BlockRulesList200;
  Errors: BlockRulesList500;
};

/**
 * @description The request has succeeded.
 */
export type BlockRulesAdd200 = any;

/**
 * @description Server error
 */
export type BlockRulesAdd500 = ApiError;

export type BlockRulesAddMutationRequest = AddItemBlockRulesRequest;

export type BlockRulesAddMutationResponse = BlockRulesAdd200;

export type BlockRulesAddMutation = {
  Response: BlockRulesAdd200;
  Request: BlockRulesAddMutationRequest;
  Errors: BlockRulesAdd500;
};

export type BlockRulesDeletePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description The request has succeeded.
 */
export type BlockRulesDelete200 = any;

/**
 * @description Server error
 */
export type BlockRulesDelete500 = ApiError;

export type BlockRulesDeleteMutationResponse = BlockRulesDelete200;

export type BlockRulesDeleteMutation = {
  Response: BlockRulesDelete200;
  PathParams: BlockRulesDeletePathParams;
  Errors: BlockRulesDelete500;
};

export type FeedTagsListQueryParams = {
  /**
   * @type string | undefined
   */
  feedId?: string;
  /**
   * @type string | undefined
   */
  tagId?: string;
};

/**
 * @description The request has succeeded.
 */
export type FeedTagsList200 = ListFeedTagsResponse;

/**
 * @description Server error
 */
export type FeedTagsList500 = ApiError;

export type FeedTagsListQueryResponse = FeedTagsList200;

export type FeedTagsListQuery = {
  Response: FeedTagsList200;
  QueryParams: FeedTagsListQueryParams;
  Errors: FeedTagsList500;
};

/**
 * @description The request has succeeded.
 */
export type FeedTagsManage200 = any;

/**
 * @description Server error
 */
export type FeedTagsManage500 = ApiError;

export type FeedTagsManageMutationRequest = ManageFeedTagsRequest;

export type FeedTagsManageMutationResponse = FeedTagsManage200;

export type FeedTagsManageMutation = {
  Response: FeedTagsManage200;
  Request: FeedTagsManageMutationRequest;
  Errors: FeedTagsManage500;
};

export type FeedsListQueryParams = {
  /**
   * @type string | undefined
   */
  tagId?: string;
};

/**
 * @description The request has succeeded.
 */
export type FeedsList200 = ListFeedsResponse;

/**
 * @description Server error
 */
export type FeedsList500 = ApiError;

export type FeedsListQueryResponse = FeedsList200;

export type FeedsListQuery = {
  Response: FeedsList200;
  QueryParams: FeedsListQueryParams;
  Errors: FeedsList500;
};

/**
 * @description The request has succeeded.
 */
export type FeedsCreate200 = CreateFeedResponse;

/**
 * @description Server error
 */
export type FeedsCreate500 = ApiError;

export type FeedsCreateMutationRequest = CreateFeedRequest;

export type FeedsCreateMutationResponse = FeedsCreate200;

export type FeedsCreateMutation = {
  Response: FeedsCreate200;
  Request: FeedsCreateMutationRequest;
  Errors: FeedsCreate500;
};

/**
 * @description The request has succeeded.
 */
export type FeedsExportOpml200 = ExportOpmlResponse;

/**
 * @description Server error
 */
export type FeedsExportOpml500 = ApiError;

export type FeedsExportOpmlMutationRequest = ExportOpmlRequest;

export type FeedsExportOpmlMutationResponse = FeedsExportOpml200;

export type FeedsExportOpmlMutation = {
  Response: FeedsExportOpml200;
  Request: FeedsExportOpmlMutationRequest;
  Errors: FeedsExportOpml500;
};

/**
 * @description The request has succeeded.
 */
export type FeedsImportOpml200 = ImportOpmlResponse;

/**
 * @description Server error
 */
export type FeedsImportOpml500 = ApiError;

export type FeedsImportOpmlMutationRequest = ImportOpmlRequest;

export type FeedsImportOpmlMutationResponse = FeedsImportOpml200;

export type FeedsImportOpmlMutation = {
  Response: FeedsImportOpml200;
  Request: FeedsImportOpmlMutationRequest;
  Errors: FeedsImportOpml500;
};

/**
 * @description The request has succeeded.
 */
export type FeedsRefresh200 = RefreshFeedsResponse;

/**
 * @description Server error
 */
export type FeedsRefresh500 = ApiError;

export type FeedsRefreshMutationRequest = RefreshFeedsRequest;

export type FeedsRefreshMutationResponse = FeedsRefresh200;

export type FeedsRefreshMutation = {
  Response: FeedsRefresh200;
  Request: FeedsRefreshMutationRequest;
  Errors: FeedsRefresh500;
};

/**
 * @description The request has succeeded.
 */
export type FeedsSuspend200 = any;

/**
 * @description Server error
 */
export type FeedsSuspend500 = ApiError;

export type FeedsSuspendMutationRequest = SuspendFeedsRequest;

export type FeedsSuspendMutationResponse = FeedsSuspend200;

export type FeedsSuspendMutation = {
  Response: FeedsSuspend200;
  Request: FeedsSuspendMutationRequest;
  Errors: FeedsSuspend500;
};

export type FeedsDeletePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description The request has succeeded.
 */
export type FeedsDelete200 = any;

/**
 * @description Server error
 */
export type FeedsDelete500 = ApiError;

export type FeedsDeleteMutationResponse = FeedsDelete200;

export type FeedsDeleteMutation = {
  Response: FeedsDelete200;
  PathParams: FeedsDeletePathParams;
  Errors: FeedsDelete500;
};

export type ItemReadsListQueryParams = {
  /**
   * @type string | undefined, date-time
   */
  since?: string;
  /**
   * @type integer | undefined, int32
   */
  pageSize?: number;
  /**
   * @type string | undefined
   */
  pageToken?: string;
};

/**
 * @description The request has succeeded.
 */
export type ItemReadsList200 = ListItemReadResponse;

/**
 * @description Server error
 */
export type ItemReadsList500 = ApiError;

export type ItemReadsListQueryResponse = ItemReadsList200;

export type ItemReadsListQuery = {
  Response: ItemReadsList200;
  QueryParams: ItemReadsListQueryParams;
  Errors: ItemReadsList500;
};

export type ItemsListQueryParams = {
  /**
   * @type string | undefined
   */
  feedId?: string;
  /**
   * @type boolean | undefined
   */
  isRead?: boolean;
  /**
   * @type string | undefined
   */
  tagId?: string;
  /**
   * @type string | undefined, date-time
   */
  since?: string;
  /**
   * @type integer | undefined, int32
   */
  pageSize?: number;
  /**
   * @type string | undefined
   */
  pageToken?: string;
};

/**
 * @description The request has succeeded.
 */
export type ItemsList200 = ListItemsResponse;

/**
 * @description Server error
 */
export type ItemsList500 = ApiError;

export type ItemsListQueryResponse = ItemsList200;

export type ItemsListQuery = {
  Response: ItemsList200;
  QueryParams: ItemsListQueryParams;
  Errors: ItemsList500;
};

/**
 * @description The request has succeeded.
 */
export type ItemsUpdateStatus200 = any;

/**
 * @description Server error
 */
export type ItemsUpdateStatus500 = ApiError;

export type ItemsUpdateStatusMutationRequest = UpdateItemStatusRequest;

export type ItemsUpdateStatusMutationResponse = ItemsUpdateStatus200;

export type ItemsUpdateStatusMutation = {
  Response: ItemsUpdateStatus200;
  Request: ItemsUpdateStatusMutationRequest;
  Errors: ItemsUpdateStatus500;
};

export type ItemsGetPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description The request has succeeded.
 */
export type ItemsGet200 = GetItemResponse;

/**
 * @description Server error
 */
export type ItemsGet500 = ApiError;

export type ItemsGetQueryResponse = ItemsGet200;

export type ItemsGetQuery = {
  Response: ItemsGet200;
  PathParams: ItemsGetPathParams;
  Errors: ItemsGet500;
};

/**
 * @description The request has succeeded.
 */
export type TagsList200 = ListTagsResponse;

/**
 * @description Server error
 */
export type TagsList500 = ApiError;

export type TagsListQueryResponse = TagsList200;

export type TagsListQuery = {
  Response: TagsList200;
  Errors: TagsList500;
};

/**
 * @description The request has succeeded.
 */
export type TagsCreate200 = CreateTagResponse;

/**
 * @description Server error
 */
export type TagsCreate500 = ApiError;

export type TagsCreateMutationRequest = CreateTagRequest;

export type TagsCreateMutationResponse = TagsCreate200;

export type TagsCreateMutation = {
  Response: TagsCreate200;
  Request: TagsCreateMutationRequest;
  Errors: TagsCreate500;
};

export type TagsDeletePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description The request has succeeded.
 */
export type TagsDelete200 = any;

/**
 * @description Server error
 */
export type TagsDelete500 = ApiError;

export type TagsDeleteMutationResponse = TagsDelete200;

export type TagsDeleteMutation = {
  Response: TagsDelete200;
  PathParams: TagsDeletePathParams;
  Errors: TagsDelete500;
};

/**
 * @description The request has succeeded.
 */
export type URLRulesList200 = ListURLParsingRulesResponse;

/**
 * @description Server error
 */
export type URLRulesList500 = ApiError;

export type URLRulesListQueryResponse = URLRulesList200;

export type URLRulesListQuery = {
  Response: URLRulesList200;
  Errors: URLRulesList500;
};

/**
 * @description The request has succeeded.
 */
export type URLRulesAdd200 = AddURLParsingRuleResponse;

/**
 * @description Server error
 */
export type URLRulesAdd500 = ApiError;

export type URLRulesAddMutationRequest = AddURLParsingRuleRequest;

export type URLRulesAddMutationResponse = URLRulesAdd200;

export type URLRulesAddMutation = {
  Response: URLRulesAdd200;
  Request: URLRulesAddMutationRequest;
  Errors: URLRulesAdd500;
};

export type URLRulesDeletePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description The request has succeeded.
 */
export type URLRulesDelete200 = any;

/**
 * @description Server error
 */
export type URLRulesDelete500 = ApiError;

export type URLRulesDeleteMutationResponse = URLRulesDelete200;

export type URLRulesDeleteMutation = {
  Response: URLRulesDelete200;
  PathParams: URLRulesDeletePathParams;
  Errors: URLRulesDelete500;
};
