/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/block-rules": {
    get: operations["BlockRules_list"];
    post: operations["BlockRules_add"];
  };
  "/block-rules/{id}": {
    delete: operations["BlockRules_delete"];
  };
  "/feed-tags": {
    get: operations["FeedTags_list"];
  };
  "/feed-tags/manage": {
    post: operations["FeedTags_manage"];
  };
  "/feeds": {
    get: operations["Feeds_list"];
    post: operations["Feeds_create"];
  };
  "/feeds/export-opml": {
    post: operations["Feeds_exportOpml"];
  };
  "/feeds/import-opml": {
    post: operations["Feeds_importOpml"];
  };
  "/feeds/refresh": {
    post: operations["Feeds_refresh"];
  };
  "/feeds/suspend": {
    post: operations["Feeds_suspend"];
  };
  "/feeds/{id}": {
    delete: operations["Feeds_delete"];
  };
  "/item-reads": {
    get: operations["ItemReads_list"];
  };
  "/items": {
    get: operations["Items_list"];
  };
  "/items/status": {
    post: operations["Items_updateStatus"];
  };
  "/items/{id}": {
    get: operations["Items_get"];
  };
  "/tags": {
    get: operations["Tags_list"];
    post: operations["Tags_create"];
  };
  "/tags/{id}": {
    delete: operations["Tags_delete"];
  };
  "/url-rules": {
    get: operations["URLRules_list"];
    post: operations["URLRules_add"];
  };
  "/url-rules/{id}": {
    delete: operations["URLRules_delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AddItemBlockRuleInput: {
      ruleType: string;
      value: string;
      domain?: string;
    };
    AddItemBlockRulesRequest: {
      rules: components["schemas"]["AddItemBlockRuleInput"][];
    };
    AddURLParsingRuleRequest: {
      domain: string;
      ruleType: string;
      pattern: string;
    };
    AddURLParsingRuleResponse: {
      rule: components["schemas"]["URLParsingRule"];
    };
    ApiError: {
      code: string;
      message: string;
    };
    CreateFeedRequest: {
      url: string;
      tagIds: string[];
    };
    CreateFeedResponse: {
      feed: components["schemas"]["Feed"];
    };
    CreateTagRequest: {
      name: string;
    };
    CreateTagResponse: {
      tag: components["schemas"]["Tag"];
    };
    ExportOpmlRequest: {
      ids: string[];
    };
    ExportOpmlResponse: {
      /** Format: byte */
      opmlContent: string;
    };
    Feed: {
      id: string;
      url: string;
      link?: string;
      title: string;
      /** Format: date-time */
      lastFetchedAt?: string;
      /** Format: date-time */
      nextFetchAt?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      tags: components["schemas"]["Tag"][];
      unreadCount: string;
    };
    FeedFetchStatus: {
      feedId: string;
      success: boolean;
      /** Format: int32 */
      newItemsCount: number;
      errorMessage?: string;
    };
    FeedTag: {
      feedId: string;
      tagId: string;
    };
    GetItemResponse: {
      item?: components["schemas"]["Item"];
    };
    ImportFailedFeed: {
      url: string;
      errorMessage: string;
    };
    ImportOpmlRequest: {
      /** Format: byte */
      opmlContent: string;
    };
    ImportOpmlResponse: {
      /** Format: int32 */
      total: number;
      /** Format: int32 */
      success: number;
      /** Format: int32 */
      skipped: number;
      failedFeeds: components["schemas"]["ImportFailedFeed"][];
    };
    Item: {
      id: string;
      url: string;
      title: string;
      description: string;
      /** Format: date-time */
      publishedAt: string;
      feedId: string;
      isRead: boolean;
      author: string;
      content: string;
      imageUrl: string;
      categories: string;
      /** Format: date-time */
      createdAt: string;
    };
    ItemBlockRule: {
      id: string;
      ruleType: string;
      value: string;
      domain?: string;
    };
    ItemRead: {
      itemId: string;
      isRead: boolean;
      /** Format: date-time */
      updatedAt: string;
    };
    ListFeedTagsResponse: {
      feedTags: components["schemas"]["FeedTag"][];
    };
    ListFeedsResponse: {
      feeds: components["schemas"]["Feed"][];
    };
    ListItemBlockRulesResponse: {
      rules: components["schemas"]["ItemBlockRule"][];
    };
    ListItemReadResponse: {
      itemReads: components["schemas"]["ItemRead"][];
      nextPageToken: string;
    };
    ListItemsResponse: {
      items: components["schemas"]["Item"][];
      nextPageToken: string;
    };
    ListTagsResponse: {
      tags: components["schemas"]["Tag"][];
      totalUnreadCount: string;
    };
    ListURLParsingRulesResponse: {
      rules: components["schemas"]["URLParsingRule"][];
    };
    ManageFeedTagsRequest: {
      feedIds: string[];
      addTagIds: string[];
      removeTagIds: string[];
    };
    RefreshFeedsRequest: {
      ids: string[];
    };
    RefreshFeedsResponse: {
      results: components["schemas"]["FeedFetchStatus"][];
    };
    SuspendFeedsRequest: {
      ids: string[];
      suspendSeconds: string;
    };
    Tag: {
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      unreadCount: string;
      feedCount: string;
    };
    URLParsingRule: {
      id: string;
      domain: string;
      ruleType: string;
      pattern: string;
    };
    UpdateItemStatusRequest: {
      ids: string[];
      isRead?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  BlockRules_list: {
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListItemBlockRulesResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  BlockRules_add: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddItemBlockRulesRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  BlockRules_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  FeedTags_list: {
    parameters: {
      query?: {
        feedId?: string;
        tagId?: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListFeedTagsResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  FeedTags_manage: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManageFeedTagsRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_list: {
    parameters: {
      query?: {
        tagId?: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListFeedsResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFeedRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["CreateFeedResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_exportOpml: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportOpmlRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ExportOpmlResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_importOpml: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportOpmlRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ImportOpmlResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_refresh: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshFeedsRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["RefreshFeedsResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_suspend: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuspendFeedsRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Feeds_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  ItemReads_list: {
    parameters: {
      query?: {
        since?: string;
        pageSize?: number;
        pageToken?: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListItemReadResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Items_list: {
    parameters: {
      query?: {
        feedId?: string;
        isRead?: boolean;
        tagId?: string;
        since?: string;
        pageSize?: number;
        pageToken?: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListItemsResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Items_updateStatus: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemStatusRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Items_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["GetItemResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Tags_list: {
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListTagsResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Tags_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTagRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["CreateTagResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Tags_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  URLRules_list: {
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["ListURLParsingRulesResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  URLRules_add: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddURLParsingRuleRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["AddURLParsingRuleResponse"];
        };
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  URLRules_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        content: never;
      };
      /** @description Server error */
      500: {
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
