// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Feed struct {
	ID          string  `json:"id"`
	Url         string  `json:"url"`
	Link        *string `json:"link"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Lang        *string `json:"lang"`
	ImageUrl    *string `json:"image_url"`
	Copyright   *string `json:"copyright"`
	FeedType    *string `json:"feed_type"`
	FeedVersion *string `json:"feed_version"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type FeedFetcher struct {
	FeedID        string  `json:"feed_id"`
	Etag          *string `json:"etag"`
	LastModified  *string `json:"last_modified"`
	LastFetchedAt *string `json:"last_fetched_at"`
	NextFetch     *string `json:"next_fetch"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type FeedItem struct {
	FeedID      string  `json:"feed_id"`
	ItemID      string  `json:"item_id"`
	PublishedAt *string `json:"published_at"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type FeedTag struct {
	FeedID    string `json:"feed_id"`
	TagID     string `json:"tag_id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Item struct {
	ID          string  `json:"id"`
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	PublishedAt *string `json:"published_at"`
	Author      *string `json:"author"`
	Guid        *string `json:"guid"`
	Content     *string `json:"content"`
	ImageUrl    *string `json:"image_url"`
	Categories  *string `json:"categories"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type ItemRead struct {
	ItemID    string  `json:"item_id"`
	IsRead    int64   `json:"is_read"`
	ReadAt    *string `json:"read_at"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

type Tag struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UrlParsingRule struct {
	ID        string `json:"id"`
	Domain    string `json:"domain"`
	RuleType  string `json:"rule_type"`
	Pattern   string `json:"pattern"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
