// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (
  uuid,
  url,
  link,
  title,
  description,
  language,
  image_url,
  copyright,
  feed_type,
  feed_version
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING uuid, url, link, title, description, language, image_url, copyright, feed_type, feed_version, last_fetched_at, created_at, updated_at
`

type CreateFeedParams struct {
	Uuid        string  `json:"uuid"`
	Url         string  `json:"url"`
	Link        *string `json:"link"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Language    *string `json:"language"`
	ImageUrl    *string `json:"image_url"`
	Copyright   *string `json:"copyright"`
	FeedType    *string `json:"feed_type"`
	FeedVersion *string `json:"feed_version"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Uuid,
		arg.Url,
		arg.Link,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.ImageUrl,
		arg.Copyright,
		arg.FeedType,
		arg.FeedVersion,
	)
	var i Feed
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.ImageUrl,
		&i.Copyright,
		&i.FeedType,
		&i.FeedVersion,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeedItem = `-- name: CreateFeedItem :exec
INSERT INTO feed_items (
  feed_id,
  item_id
) VALUES (
  ?, ?
)
ON CONFLICT(feed_id, item_id) DO NOTHING
`

type CreateFeedItemParams struct {
	FeedID string `json:"feed_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) error {
	_, err := q.db.ExecContext(ctx, createFeedItem, arg.FeedID, arg.ItemID)
	return err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  id,
  url,
  title,
  description,
  published_at,
  guid
) VALUES (
  ?, ?, ?, ?, ?, ?
)
ON CONFLICT(url) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  published_at = excluded.published_at,
  guid = excluded.guid,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, url, title, description, published_at, guid, created_at, updated_at
`

type CreateItemParams struct {
	ID          string  `json:"id"`
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	PublishedAt *string `json:"published_at"`
	Guid        *string `json:"guid"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Guid,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Guid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItemRead = `-- name: CreateItemRead :exec
INSERT INTO item_reads (
  item_id
) VALUES (
  ?
)
ON CONFLICT(item_id) DO NOTHING
`

func (q *Queries) CreateItemRead(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, createItemRead, itemID)
	return err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM
  feeds
WHERE
  uuid = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, uuid)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT
  uuid, url, link, title, description, language, image_url, copyright, feed_type, feed_version, last_fetched_at, created_at, updated_at
FROM
  feeds
WHERE
  uuid = ?
`

func (q *Queries) GetFeed(ctx context.Context, uuid string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, uuid)
	var i Feed
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.ImageUrl,
		&i.Copyright,
		&i.FeedType,
		&i.FeedVersion,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT
  uuid, url, link, title, description, language, image_url, copyright, feed_type, feed_version, last_fetched_at, created_at, updated_at
FROM
  feeds
ORDER BY
  created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.Uuid,
			&i.Url,
			&i.Link,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.ImageUrl,
			&i.Copyright,
			&i.FeedType,
			&i.FeedVersion,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE
  feeds
SET
  link = ?,
  title = ?,
  description = ?,
  language = ?,
  image_url = ?,
  copyright = ?,
  feed_type = ?,
  feed_version = ?,
  last_fetched_at = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  uuid = ?
RETURNING uuid, url, link, title, description, language, image_url, copyright, feed_type, feed_version, last_fetched_at, created_at, updated_at
`

type UpdateFeedParams struct {
	Link          *string `json:"link"`
	Title         *string `json:"title"`
	Description   *string `json:"description"`
	Language      *string `json:"language"`
	ImageUrl      *string `json:"image_url"`
	Copyright     *string `json:"copyright"`
	FeedType      *string `json:"feed_type"`
	FeedVersion   *string `json:"feed_version"`
	LastFetchedAt *string `json:"last_fetched_at"`
	Uuid          string  `json:"uuid"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.Link,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.ImageUrl,
		arg.Copyright,
		arg.FeedType,
		arg.FeedVersion,
		arg.LastFetchedAt,
		arg.Uuid,
	)
	var i Feed
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.ImageUrl,
		&i.Copyright,
		&i.FeedType,
		&i.FeedVersion,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
