/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as ItemsRouteImport } from './routes/_items'
import { Route as ItemsIndexRouteImport } from './routes/_items.index'
import { Route as ItemsItemsItemIdRouteImport } from './routes/_items.items.$itemId'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/_items',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsItemsItemIdRoute = ItemsItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => ItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ItemsIndexRoute
  '/feeds': typeof FeedsRoute
  '/tags': typeof TagsRoute
  '/items/$itemId': typeof ItemsItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/feeds': typeof FeedsRoute
  '/tags': typeof TagsRoute
  '/': typeof ItemsIndexRoute
  '/items/$itemId': typeof ItemsItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_items': typeof ItemsRouteWithChildren
  '/feeds': typeof FeedsRoute
  '/tags': typeof TagsRoute
  '/_items/': typeof ItemsIndexRoute
  '/_items/items/$itemId': typeof ItemsItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feeds' | '/tags' | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/feeds' | '/tags' | '/' | '/items/$itemId'
  id:
    | '__root__'
    | '/_items'
    | '/feeds'
    | '/tags'
    | '/_items/'
    | '/_items/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ItemsRoute: typeof ItemsRouteWithChildren
  FeedsRoute: typeof FeedsRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_items': {
      id: '/_items'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_items/': {
      id: '/_items/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/_items/items/$itemId': {
      id: '/_items/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemsItemIdRouteImport
      parentRoute: typeof ItemsRoute
    }
  }
}

interface ItemsRouteChildren {
  ItemsIndexRoute: typeof ItemsIndexRoute
  ItemsItemsItemIdRoute: typeof ItemsItemsItemIdRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIndexRoute: ItemsIndexRoute,
  ItemsItemsItemIdRoute: ItemsItemsItemIdRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ItemsRoute: ItemsRouteWithChildren,
  FeedsRoute: FeedsRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
